version: "3.8"
services:
  app:
    container_name: form-app
    image: form-service
    build: ./
    ports:
      - "8087:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3305/form_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      app_network:

  ### MySQL Database ###
  mysql:
    container_name: mysql-form
    image: mysql:8.0
    hostname: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: form_db
    networks:
      app_network:

  phpmyadmin:
    container_name: phpmyadmin-form
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    ports:
      - "6060:80"
    networks:
      app_network:

networks:
  app_network: