server:
  servlet:
    context-path: /api
  port: 8083

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /api-doc

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
  mvc:
    media-types:
      json: application/json
      multipart: multipart/form-data
      servlet:
        multipart:
          enabled: true


